# Generated by Django 4.1.4 on 2023-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='camponovo',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
