# Generated by Django 4.1.4 on 2023-01-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_camponovo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='camponovo',
        ),
    ]
